# Generated by Django 4.2 on 2023-04-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_alter_product_inventory_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory_updated_time',
            field=models.DateTimeField(blank=None),
        ),
    ]
