# Generated by Django 4.2 on 2023-04-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_alter_product_name_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory_updated_time',
            field=models.DateTimeField(),
        ),
    ]
